sudo: required
services:
  - docker

# Install Google Cloud SDK
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service_account.json.enc -out /app/service_account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
# Configure SDK with Google Cloud account info
# Login to Docker CLI
# Perform test build
# Run tests
# Build images, tag them and push to docker hub
# Apply config to k8s folder
# Imperatively update the images in the cluster
