apiVersion: cert-manager.io/v1alpha2
kind: CluserIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    emain: raghu.amachi@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solver:
      - http01:
          ingress:
            class: nginx
